# run the script
name: Cron
on:

  # manually
  workflow_dispatch:
  
  # cron
  schedule:
    - cron: 0 8 * * mon-fri # will run at 9/10 madrid time

jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run reservaSitios.sh
        env:
          USERNAME: ${{ secrets.USERNAME }}
        run: bash ./reservaSitios.sh
