# run the script
name: Cron
on:

  # manually
  workflow_dispatch:
  
  # cron
  schedule:
    - cron: 0 6 * * mon-fri # will run at 7/8 madrid time

jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run reservaSitios.sh
        run: bash ./reservaSitios.sh
